name: Sync to Bitbucket

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push a Bitbucket
        run: |
          git remote add bitbucket https://x-token-auth:${{ secrets.BITBUCKET_TOKEN }}@bitbucket.org/alberthzaid/vortex-prueba-bitbucket.git
          git push bitbucket HEAD:main --force


